name: Gerar e Enviar para o Google Drive

on:
  workflow_dispatch:
    inputs:
      link_drive:
        description: 'Link do Google Drive (Base):'
        required: true
        default: 'https://drive.google.com/uc?id=1kk-OsN3R02flYm2Nl0kYZ7qI3JdzhwB_&export=download'
      link_mestre:
        description: 'Link da Fonte Mestre (br.m3u):'
        required: true
        default: 'https://raw.githubusercontent.com/iptv-org/iptv/master/streams/br.m3u'

jobs:
  gerar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configurar o Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar Dependências
        run: |
          pip install --upgrade pip
          pip install flet requests

      - name: Executar o Robô
        run: |
          python robo.py "${{ github.event.inputs.link_drive }}" "${{ github.event.inputs.link_mestre }}"

      - name: Enviar Ficheiro para o Google Drive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          filename: 'resultado/lista.txt'
          folderId: 'ID_DA_SUA_PASTA_NO_DRIVE'
          credentials: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
          overwrite: 'true'
